databases:
  - name: lululime
    user: lululime
    plan: starter
    region: oregon

services:
  - type: web
    name: lululime
    plan: free
    region: oregon
    branch: main
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lululime
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false